language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install:
  - gem install bundler -v 2.0.2
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh
  - nvm install 13
script:
  - yarn install --check-files
  - bundle exec rubocop
  - bundle exec rake
  - cd scripts/chart && ./ci.sh
